nervosnetwork/godwoken-polyjuice

- .gitmodules
- polyjuice-tests/fuzz/Makefile
- polyjuice-tests/fuzz/mock_godwoken.hpp
1. Remove `AdvancedCodeAnalysis.push_values` for saving massive of memory (contract_code_size * 32)
2. Copy push value directly from code data when needed
evmone changes:
https://github.com/TheWaWaR/evmone/commit/bfad45299ec637f4b90a5ed7ec6173f25653b348
https://github.com/TheWaWaR/evmone/commit/f7bcd2368348e28abd99443239f249f9431d41e8
> fix: update evmone to fix out of memory error

- c/polyjuice.h
- polyjuice-tests/fuzz/Makefile
- polyjuice-tests/fuzz/polyjuice_generator_fuzzer.cc
The default res.ges_left = 3980426352635039463 which will return to evmone when inner call is failed.
fix https://github.com/Flouse/godwoken-polyjuice/runs/3188815701?check_suite_focus=true#step:9:446
> fix(call): set default evmc_result.gas_left to 0

- .github/workflows/ci.yml
- Makefile
- devtools/ci/integration-test.sh
- solidity/erc20/README.md
1. add a command in Makefile to build the ERC20 contract via docker image.
2. add a command to verify the checksum of the binary using `blake2b`.
_Originally posted by @jjyr in https://github.com/nervosnetwork/godwoken-polyjuice/issues/83#issuecomment-914107279_
> chore: add validation of sudt-erc20-proxy contract.bin checksum into CI

- README.md
- docs/EVM-compatible.md
Polyjuice aims at 100% EVM compatibility as a goal, meaning we plan to support all smart contracts supported by the latest Ethereum hardfork version. But in the current version, something is incompatible with EVM.
This PR adds more docs about EVM compatibility. See [EVM-compatible.md](https://github.com/nervosnetwork/godwoken-polyjuice/docs/EVM-compatible.md) and [Addition-Features.md](https://github.com/nervosnetwork/godwoken-polyjuice/docs/Addition-Features.md) for more details.
> docs: comparison with EVM

- Makefile
- README.md
- c/eth_addr_reg.c
- c/other_contracts.h
- c/polyjuice.h
- c/polyjuice.mol
- c/polyjuice_globals.h
- c/polyjuice_utils.h
- c/sudt_contracts.h
- polyjuice-tests/src/helper.rs
- polyjuice-tests/src/test_cases/call_selfdestruct.rs
- polyjuice-tests/src/test_cases/erc20.rs
- polyjuice-tests/src/test_cases/eth_addr_reg.rs
- polyjuice-tests/src/test_cases/eth_to_godwoken_addr.rs
- polyjuice-tests/src/test_cases/get_block_info.rs
- polyjuice-tests/src/test_cases/invalid_sudt_erc20_proxy.rs
- polyjuice-tests/src/test_cases/metamask_transactions.rs
- polyjuice-tests/src/test_cases/mod.rs
- polyjuice-tests/src/test_cases/parse_log_event.rs
- polyjuice-tests/src/test_cases/selfdestruct.rs
- polyjuice-tests/src/test_cases/simple_transfer.rs
- polyjuice-tests/src/test_cases/sudt_erc20_proxy.rs
In the latest version of Polyjuice, the EOA addresses are native `eth_address`, which is the rightmost 160 bits of a Keccak hash of an ECDSA public key.
- Support new L2TX format with native eth_address
* new L2TX format: `polyjuice_args.header[0..7] = "ETHPOLY"`
- test: mock transfer from EoA to EoA using Metamask
- Update docs
* update the header format of Polyjuice.args
> Interoperability: support new L2TX format with native `eth_address`

- Makefile
- polyjuice-tests/Cargo.lock
- fetch ckb-binary-patcher with [Remove atomic instructions] feature"
from the master branch of nervosnetwork/ckb-binary-patcher.
> https://github.com/nervosnetwork/ckb-binary-patcher/commit/b9489de4b3b9d59bc29bce945279bc6f28413113
> chore: update nervosnetwork/ckb-binary-patcher

- c/contracts.h
> pre-compiled contract `bn256_pairing` not supported yet,
due to its high cycle cost
bn256_pairing will not be implemented in the current Godwoken version.
```
=================================================================
==5875==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 188 byte(s) in 188 object(s) allocated from:
#0 0x50a6dd in malloc /local/mnt/workspace/bcain_clang_bcain-ubuntu_7561/final/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x669086 in bn256_pairing_istanbul(gw_context_t*, unsigned char const*, unsigned long, bool, unsigned char const*, unsigned long, unsigned char**, unsigned long*) /home/runner/work/godwoken-polyjuice/godwoken-polyjuice/polyjuice-tests/fuzz/../../c/contracts.h:880:40
#2 0x6727d2 in call(evmc_host_context*, …
```
> Fix memory leaks in bn256_pairing_istanbul()

- README.md
- c/polyjuice.h
- c/polyjuice_globals.h
- c/polyjuice_utils.h
- polyjuice-tests/src/helper.rs
- ### Update Creator account script
```
code_hash: Polyjuice_validator_type_script_hash
hash_type: type
args:
rollup_type_hash : [u8; 32]
sudt_id          : u32          (little endian, the token id)
eth_addr_reg_id  : u32          (little endian, the ETH_Address_Registry Contract id)
```
Polyjuice creator account is a godwoken account for creating Polyjuice contract account. This account can only be created by [meta contract](https://github.com/nervosnetwork/godwoken/blob/master/docs/life_of_a_godwoken_transaction.md#metacontract), and the account id is used as the chain id in Polyjuice. The `sudt_id` field in script args is the sUDT token current Polyjuice instance bind to as [`pETH`](https://github.com/nervosnetwork/godwoken/blob/master/docs/life_of_a_polyjuice_transaction.md#peth). …
> refactor: add eth_addr_reg_id into creator_script.args

- polyjuice-tests/src/helper.rs
see [fix(tool): set rollup_type_hash into the args of eth_addr_reg_script](https://github.com/nervosnetwork/godwoken/pull/587/commits/4669cb02ca1732aab5bcc77f7a1ef92896ef74ab) in [Godwoken](https://github.com/nervosnetwork/godwoken/pull/587)
> test: set rollup_type_hash into the args of eth_addr_reg_script

- README.md
- docs/Addition-Features.md
- docs/EVM-compatible.md
* Value (pETH) transfer from EOA to EOA directly is not supported.
> Workaround: Since pETH (CKB) is a layer2 sUDT, it could be transfered through the [sUDT_ERC20_Proxy](https://github.com/nervosnetwork/godwoken-polyjuice/blob/3f1ad5b/solidity/erc20/README.md) contract's `transfer function`.
* The `transfer value` can not exceed uint128:MAX
- https://github.com/nervosnetwork/godwoken-web3/pull/207
> docs: update EVM-compatible.md

- .github/workflows/ci.yml
~~delete kicker_ref: refs/pull/179/head~~
> chore(CI): remove kicker_ref in the inputs of reusable-integration-test-v1

- .gitignore
- .vscode/launch.json
- polyjuice-tests/fuzz/README.md
1. Compile Polyjuice generator on x86
```bash
cd polyjuice-tests/fuzz
make build/polyjuice_generator_fuzzer
```
2. Construct `pre_defined_test_case` in [polyjuice_generator_fuzzer.cc](./polyjuice_generator_fuzzer.cc)
3. Run `build/polyjuice_generator_fuzzer_log` with GDB debugger
see: launch.json
> docs: How to debug Polyjuice generator on x86

- docs/EVM-compatible.md
Add docs about why some eth contracts could run into errors due to memory limit.
> docs: about evm memory limit on ckb-vm

- Makefile
- c/polyjuice.h
- c/polyjuice_globals.h
- devtools/ci/integration-test.sh
- polyjuice-tests/src/helper.rs
Polyjuice [v0.8.12](https://github.com/nervosnetwork/godwoken-polyjuice/releases/tag/v0.8.12) has been updated on Godwoken mainnet_v0.
But this [commit](https://github.com/nervosnetwork/godwoken-polyjuice/commit/c927fb6ce6d5c3632e09bc5de2d1485736c56fe0) is not forward compatible on testnet_v0.
So, we need a simple hardfork mechanism to solve it.
This PR introduce TESTNET_V0_FORK1.
2022/05/18 18:05 testnet_v0 BlockHeight is [371,156](https://aggron.gwscan.com/block/0x6ea422206813ffe3a3058af56ae1fa4f5178a566abed9f76ca502eb0065028d8).
Plan to hardfork at block 380000.
> fix(testnet_v0): add `TESTNET_V0_FORK1`

- c/polyjuice.h
- c/polyjuice_errors.h
- c/polyjuice_globals.h
- polyjuice-tests/Cargo.lock
- polyjuice-tests/Cargo.toml
- polyjuice-tests/src/test_cases/address_collision.rs
- polyjuice-tests/src/test_cases/mod.rs
Fix address collision between EOA account address and contract address created by `create`/`create2`.
We can overwrite the mapping if it's an EOA account and the nonce is 0.
- This PR depends on https://github.com/nervosnetwork/godwoken-scripts/pull/119
> Fix address collision between contract and unused EOA

- .github/workflows/ci.yml
With this update, we can create PR from fork repos now.
The target godwoken-tests workflow: https://github.com/nervosnetwork/godwoken-tests/blob/simplify-workflow/.github/workflows/reusable-integration-test-v1.yml
> feat: reuse simplified godwoken-test workflow

- polyjuice-tests/Cargo.lock
- polyjuice-tests/Cargo.toml
- chore(deps): Bumps [regex](https://github.com/rust-lang/regex) 1.5.6
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/rust-lang/regex/blob/master/CHANGELOG.md">regex's changelog</a>.</em></p>
<blockquote>
<h1>1.5.6 (2022-05-20)</h1>
<p>This release includes a few bug fixes, including a bug that produced incorrect
matches when a non-greedy <code>?</code> operator was used.</p>
<ul>
<li>[BUG <a href="https://github-redirect.dependabot.com/rust-lang/regex/issues/680">#680</a>](<a href="https://github-redirect.dependabot.com/rust-lang/regex/issues/680">rust-lang/regex#680</a>):
Fixes a bug where <code>[[:alnum:][:^ascii:]]</code> dropped <code>[:alnum:]</code> from the class.</li>
<li>[BUG <a href="https://github-redirect.dependabot.com/rust-lang/regex/i …
> chore: update deps of polyjuice-tests

- polyjuice-tests/Cargo.lock
- polyjuice-tests/tests/ethereum_test.rs
Add an assert to compare logs hash in VM test.
**Generated State Transition Tests**
Contains transactions that are to be executed on a state pre given the environment env and must end up with post results post
**About log hash of the transaction logs in the `Post Section`**
https://ethereum-tests.readthedocs.io/en/latest/test_types/gstate_tests.html#post-section
> test: handle logs hash in post of ethereum tests

- c/polyjuice_globals.h
- devtools/ci/integration-test.sh
GCC interpretes literal constants as 64 bits integers.
> warning: integer constant is too large for its type static uint128_t g_gas_price = 0xffffffffffffffffffffffffffffffffu;
=>
```js
UINT128_MAX = uint128_t(__int128_t(-1L))
= 340282366920938463463374607431768211455
= 0xffffffffffffffffffffffffffffffffu
```
> fix: g_gas_price constant is too large for its type

- c/polyjuice.h
- c/polyjuice_globals.h
- polyjuice-tests/Cargo.lock
- polyjuice-tests/src/ctx.rs
- polyjuice-tests/src/helper.rs
- polyjuice-tests/src/test_cases/native_token_transfer.rs
- polyjuice-tests/src/test_cases/recover_account.rs
In this pr, a new EoA account is created during native token transferring if the `to_address` is not registered.
And fix the test due to updates of recover account from godwoken.
- https://github.com/nervosnetwork/godwoken-polyjuice/pull/173
> Create new account during transferring if the to_address is not registered.

- c/polyjuice.h
- polyjuice-tests/src/test_cases/native_token_transfer.rs
- fix https://github.com/nervosnetwork/godwoken-web3/issues/518
The `used_gas` was set with the wrong value.
> Fix wrong used_gas of native transfer in polyjuice_system_log
